resolver: lts-13.12

packages:
- .
- location:
    git: https://github.com/runeksvendsen/mono-traversable.git
    commit: 5faf07d2dc2b3b67d2c138bdeb4d66b9105a1661
    subdirs:
      - mutable-containers
  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/impure-containers.git
    commit: 0f00dc9a617d5312b6fe5e9ddb9c2b4b9d0afdaf
  extra-dep: true

flags:
  impure-containers:
    unsafe-tricks: false
    bounds-checking: true
    debug: false

extra-deps:
- containers-0.5.11.0@sha256:28ad7337057442f75bc689315ab4ec7bdf5e6b2c39668f306672cecd82c02798
